// <auto-generated>
// This code was generated by FairyGUI GenCode plugin.
// Do not modify manually - changes will be overwritten.
// </auto-generated>

using FairyGUI;

namespace GameLogic
{
    /// <summary>
    /// LoginUIPanel 窗口设计类 - 自动生成，请勿手动修改。
    /// 业务逻辑请在 LoginUIPanel.cs 中实现。
    /// </summary>
    public partial class LoginUIPanel : FairyUIWindow
    {
        /// <summary>
        /// 包名称常量。
        /// </summary>
        public const string PackageNameConst = "LoginUI";

        /// <summary>
        /// 组件名称常量。
        /// </summary>
        public const string ComponentNameConst = "LoginUIPanel";

        /// <inheritdoc/>
        public override string PackageName => PackageNameConst;

        /// <inheritdoc/>
        public override string ComponentName => ComponentNameConst;

        #region UI Fields

        public GButton BtnEnterGame;
        public Controller Ctrl;
        public Controller CtrlDebug;
        public Controller CtrlFinger;
        public Controller CtrlLoading;
        public Controller CtrlPlatform;
        public GGroup GroupEnterTip;
        public GLoader LoaderEnter;
        public Transition TransFingerShow;
        public Transition TransShow;
        public GTextField TxtEnterGame;

        #endregion

        /// <inheritdoc/>
        protected override void BindMemberProperty()
        {
            base.BindMemberProperty();

            // 自动绑定 UI 组件字段
            BtnEnterGame = (GButton)GetChild("btnEnterGame");
            Ctrl = GetController("ctrl");
            CtrlDebug = GetController("ctrlDebug");
            CtrlFinger = GetController("ctrlFinger");
            CtrlLoading = GetController("ctrlLoading");
            CtrlPlatform = GetController("ctrlPlatform");
            GroupEnterTip = (GGroup)GetChild("groupEnterTip");
            LoaderEnter = (GLoader)GetChild("loaderEnter");
            TransFingerShow = GetTransition("transFingerShow");
            TransShow = GetTransition("transShow");
            TxtEnterGame = (GTextField)GetChild("txtEnterGame");
        }
    }
}