// <auto-generated>
// This code was generated by FairyGUI GenCode plugin.
// Do not modify manually - changes will be overwritten.
// </auto-generated>

using FairyGUI;

namespace GameLogic
{
    /// <summary>
    /// LoginSignPopPanel 窗口设计类 - 自动生成，请勿手动修改。
    /// 业务逻辑请在 LoginSignPopPanel.cs 中实现。
    /// </summary>
    public partial class LoginSignPopPanel : FairyUIWindow
    {
        /// <summary>
        /// 包名称常量。
        /// </summary>
        public const string PackageNameConst = "LoginUI";

        /// <summary>
        /// 组件名称常量。
        /// </summary>
        public const string ComponentNameConst = "LoginSignPopPanel";

        /// <inheritdoc/>
        public override string PackageName => PackageNameConst;

        /// <inheritdoc/>
        public override string ComponentName => ComponentNameConst;

        #region UI Fields

        public GButton Btngoogle;

        #endregion

        /// <inheritdoc/>
        protected override void BindMemberProperty()
        {
            base.BindMemberProperty();

            // 自动绑定 UI 组件字段
            Btngoogle = (GButton)GetChild("btngoogle");
        }
    }
}