// <auto-generated>
// This code was generated by FairyGUI GenCode plugin.
// Do not modify manually - changes will be overwritten.
// </auto-generated>

using FairyGUI;

namespace GameLogic
{
    /// <summary>
    /// LoginUIPanel 窗口设计类 - 自动生成，请勿手动修改。
    /// 业务逻辑请在 LoginUIPanel.cs 中实现。
    /// </summary>
    public partial class LoginUIPanel : FairyUIWindow
    {
        /// <summary>
        /// 包名称常量。
        /// </summary>
        public const string PackageNameConst = "LoginUI";

        /// <summary>
        /// 组件名称常量。
        /// </summary>
        public const string ComponentNameConst = "LoginUIPanel";

        /// <inheritdoc/>
        public override string PackageName => PackageNameConst;

        /// <inheritdoc/>
        public override string ComponentName => ComponentNameConst;

        #region UI Fields

        public GButton BtnEnterGame;
        public GButton BtnSign;
        public Controller CtrlLoading;
        public GLoader LoaderEnter;
        public Transition TransShow;

        #endregion

        /// <inheritdoc/>
        protected override void BindMemberProperty()
        {
            base.BindMemberProperty();

            // 自动绑定 UI 组件字段
            BtnEnterGame = (GButton)GetChild("btnEnterGame");
            BtnSign = (GButton)GetChild("btnSign");
            CtrlLoading = GetController("ctrlLoading");
            LoaderEnter = (GLoader)GetChild("loaderEnter");
            TransShow = GetTransition("transShow");
        }
    }
}